package com.example.kamatechs.database

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "storage_table") // User Entity represents a table within the database.
data class Storage(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val Temperature: Int,
    val Humidity: Int,
): Parcelable
